version: 2

jobs:
  build-dependencies:
    docker:
      - image: circleci/node:9
    working_directory: ~/codesandbox-client
    steps:
      - checkout
      - restore_cache:
          keys:
            - v11-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v11-dependency-cache-{{ .Branch }}
            - v11-dependency-cache
      - restore_cache:
          keys:
            - v11-standalone-dependency-cache-{{ .Branch }}-{{ checksum "standalone-packages/codesandbox-browserfs/yarn.lock" }}
            - v11-standalone-dependency-cache-{{ .Branch }}
            - v11-standalone-dependency-cache
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v11-dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/app/node_modules
            - packages/codesandbox-api/node_modules
            - packages/common/node_modules
            - packages/homepage/node_modules
            - packages/react-sandpack/node_modules
            - packages/sandpack/node_modules
      - save_cache:
          key: v11-standalone-dependency-cache-{{ .Branch }}-{{ checksum "standalone-packages/codesandbox-browserfs/yarn.lock" }}
          paths:
            - standalone-packages/codesandbox-browserfs/node_modules
      - run:
          name: Build
          command: yarn build:deps
      - save_cache:
          key: v11-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/codesandbox-client

  build-prod:
    docker:
      - image: circleci/node:9
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v11-repo-{{ .Environment.CIRCLE_SHA1 }}
      # We do this to compare sizes from these builds with master
      - restore_cache:
          key: v11-prod-app-build-cache-master
      - run:
          name: Build Application
          command: yarn build:prod
      - save_cache:
          key: v11-prod-app-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./packages/app/www
      - save_cache:
          key: v11-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./www

  test-integrations:
    docker:
      - image: codesandbox/node-puppeteer
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v11-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Start Test Server
          command: yarn start:test
          background: true
      - run:
          name: Setup BrowserStack local environment
          command: "[ -n \"$BROWSER_STACK_KEY\" ] && ./packages/app/integration-tests/BrowserStackLocal --key $BROWSER_STACK_KEY || true"
          background: true
      - run:
          name: Test Integrations
          command: |
            sleep 15
            yarn test:integrations --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "/tmp/test-results/js-test-results.xml"
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: packages/app/integration-tests/tests/__image_snapshots__/__diff_output__
          destination: image_snapshot_diff

  test-jest:
    docker:
      - image: circleci/node:9
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v11-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: yarn test --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"

  lint:
    docker:
      - image: circleci/node:9
    working_directory: ~/codesandbox-client
    steps:
      - restore_cache:
          key: v11-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint

  create-docker-image:
    machine: true
    working_directory: ~/codesandbox-client
    steps:
      - checkout
      - restore_cache:
          key: v11-prod-build-cache-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Docker Sign In
          command: "[ -n \"$DOCKER_USER\" ] && echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin || true"
      - run:
          name: Create Image
          command: "[ -n \"$DOCKER_USER\" ] && docker build -t codesandbox/client:${CIRCLE_SHA1:0:7} . || true"
      - deploy:
          name: Push Image
          command: "[ -n \"$DOCKER_USER\" ] && docker push codesandbox/client:${CIRCLE_SHA1:0:7} || true"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-dependencies
      - test-integrations:
          requires:
            - build-dependencies
      - test-jest:
          requires:
            - build-dependencies
      - lint:
          requires:
            - build-dependencies
      - build-prod:
          requires:
            - build-dependencies
      - create-docker-image:
          requires:
            - build-prod
            - lint
            - test-jest
